- name: Demo of ansible capability and scripting
  hosts: all
  vars:
    file_location: "/var/www/html/index.html"
  tasks:
    - name: Ensure apache is installed
      become: true
      package:
        name: httpd
        state: present

    - name: Ensure apache is running
      become: true
      service:
        name: httpd
        state: started
        enabled: yes


    - name: Ensure index.html is deployed as per template
      become: true
      vars:
        name: "Ziad"
        title: "Tutorial Week 7"
      template:
        dest: "{{ file_location }}"
        src: index.html.tpl